### ISSUE TITLE
[BUG] Traning crashes when tuning page or main data

### ISSUE THREAD

**Issue by majafranz** [cirKITers/MindTheQApp#23]
Various errors occur when a training is running and the main data (e.g. number of qubits) is changed during that.
Please disable inputs during training and add stop training button.

**Comment by majafranz** [comment]
+ we need to catch the "NoAnsatz" case for training

**Comment by stroblme** [comment]
re-visit after #21 and #25

**Comment by stroblme** [comment]
is this still valid with #42 ?
